default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: webpack_1_development
test:
  <<: *default
  database: webpack_1_test
production:
  <<: *default
  database: webpack_1_production
  username: root
  password:
